#!/bin/sh
# Auto-generated by TheOneKit — UserPromptSubmit hook
# Warns when user mentions keywords for uninstalled modules
# Reads t1k-modules-keywords-*.json and .t1k-module-summary.txt

SUMMARY_FILE=".t1k-module-summary.txt"
[ ! -f "$SUMMARY_FILE" ] && exit 0

# Build installed modules set from summary
INSTALLED=""
while IFS='|' read -r kit version preset modules; do
  case "$kit" in \#*|"") continue ;; esac
  INSTALLED="$INSTALLED,$modules,"
done < "$SUMMARY_FILE"

# Read user prompt from stdin
PROMPT="$(cat)"
[ -z "$PROMPT" ] && exit 0

# Convert prompt to lowercase for matching
PROMPT_LOWER="$(echo "$PROMPT" | tr '[:upper:]' '[:lower:]')"

WARNED=""
COUNT=0

# Process each keyword file
for KW_FILE in .claude/t1k-modules-keywords-*.json; do
  [ ! -f "$KW_FILE" ] && continue

  # Extract keyword:module pairs using grep/sed (no jq dependency)
  grep -o '"[^"]*": *"[^"]*"' "$KW_FILE" | grep -v 'registryVersion\|kitName' | while IFS=: read -r key val; do
    keyword=$(echo "$key" | tr -d '" ')
    module=$(echo "$val" | tr -d '" ')
    keyword_lower=$(echo "$keyword" | tr '[:upper:]' '[:lower:]')

    # Check if keyword in prompt
    case "$PROMPT_LOWER" in
      *"$keyword_lower"*) ;;
      *) continue ;;
    esac

    # Check if module installed
    case "$INSTALLED" in
      *",$module,"*) continue ;;
    esac

    # Check if already warned for this module
    case "$WARNED" in
      *",$module,"*) continue ;;
    esac

    WARNED="$WARNED,$module,"
    COUNT=$((COUNT + 1))
    [ $COUNT -gt 3 ] && break

    echo "[t1k:module-suggest] keyword=\"$keyword\" module=\"$module\" action=\"t1k modules add $module\""
  done
done
exit 0
