#!/bin/sh
# Auto-generated by TheOneKit — SessionStart hook
# Outputs installed kit/module context for AI awareness
# Reads .t1k-module-summary.txt (flat text, no JSON parsing)

SUMMARY_FILE=".t1k-module-summary.txt"
[ ! -f "$SUMMARY_FILE" ] && exit 0

echo "TheOneKit context:"
while IFS='|' read -r kit version preset modules; do
  case "$kit" in \#*|"") continue ;; esac
  if [ -n "$preset" ]; then
    echo "  Kit: $kit v$version (preset: $preset)"
  else
    echo "  Kit: $kit v$version"
  fi
  if [ -n "$modules" ]; then
    echo "  Modules: $modules"
  fi
done < "$SUMMARY_FILE"
exit 0
